### ISSUE TITLE
TypeError: GRUCell.__init__() missing 1 required positional argument: 'features'

### ISSUE THREAD

**Issue by cool-RR** [Silent-Zebra/POLA#10]
```
$ python ./jax_files/POLA_dice_jax.py --env ipd --n_update 101 --gae_lambda 1.0 --inner_steps 2 --outer_steps 200 --lr_in 0.005 --lr_out 0.003 --lr_v 0.0005 --batch_size 2000 --rollout_len 50 --print_every 1 --inner_beta 10 --outer_beta 100 --seed 1 --layers_before_gru 1 --checkpoint_every 10 --hidden_size 64
WARNING:absl:Tensorflow library not found, tensorflow.io.gfile operations will use native shim calls. GCS paths (i.e. 'gs://...') cannot be accessed.
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\Python Projects\Third-party\POLA\jax_files\POLA_dice_jax.py", line 2028, in <module>
    trainstate_th1, trainstate_val1, trainstate_th2, trainstate_val2 = get_init_trainstates(key, action_size, input_size)
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\Python Projects\Third-party\POLA\jax_files\POLA_dice_jax.py", line 1412, in get_init_trainstates
    theta_p1_params = theta_p1.init(key_p1, jnp.ones(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\Python Projects\Third-party\POLA\jax_files\POLA_dice_jax.py", line 207, in setup
    self.GRUCell = nn.GRUCell()
                   ^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\flax\linen\kw_only_dataclasses.py", line 235, in init_wrapper
    dataclass_init(self, *args, **kwargs)
TypeError: GRUCell.__init__() missing 1 required positional argument: 'features'
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

[Package versions.](https://gist.github.com/cool-RR/fb18ec947c8a7e00c46ea48c569fa651)

**Comment by cool-RR** [comment]
Thank you @Aidandos . I found the right versions to use now and created a pull request for them: https://github.com/Silent-Zebra/POLA/pull/11
